http_client:
  parameters:
    name: 'API Activation Code client'

  options-extend:
    mapping_key:
      LetsCompose\Core\HttpClient\Option\MapKeysOption:
        config: 'schema\mapping\activation-code.yaml'
        loader:
          class: LetsCompose\Core\HttpClient\Option\MapKeysOptionLoader
          config: ~
#  default_request_config:
#    for_all:
#      headers: []
#      query_params: []
#      uri_prefix: '123'
#    by_method:
#      -
#        headers: ~
#        query_params: ~
#        uri_prefix: '456'
#        apply_for: ['POST', 'GET']
#        use_defaults: false

  default_response_config:
    headers: ~

  default_response_exception_config:
    message_prefix: '[{action_name}]'
    exceptions:
      -
        class: LetsCompose\Core\Exception\InvalidLogicException
        code: 400
        message: 'Error on API Call'
        when_response_code: [400]

  actions:
    activation-codes:
      upload:
        request:
          use_defaults: true
          method: POST
          uri: /activation-code/import-file
          options:
            keys_to_camel_case: true

        response:
          options:
            mapping_key: "activation-codes.upload-file"

        response_exception:
          message_prefix: ''
          exceptions:
            \InvalidArgumentException:
              code: 400
              message: 'resource not found exception'
              default: true
#              when_response_code: [400]
